name: denaro # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2023.4.1-beta1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: denaro
#summary: Manage your personal finances
#description: |
#  A personal finance manager
icon: org.nickvision.money.svg
source-code: https://github.com/nlogozzo/NickvisionMoney
issues: https://github.com/nlogozzo/NickvisionMoney/issues
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  denaro:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/NickvisionApps/Denaro.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-subdir: NickvisionMoney.GNOME
    build-packages:
      - blueprint-compiler
      - wget
      - cargo
    override-pull: |
      craftctl default
      cargo install just
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 7.0
    override-build: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools:$HOME/.cargo/bin
      cd $CRAFT_PART_SRC_WORK
      just publish-self-contained /usr
      just install $CRAFT_PRIME
      sed -i "s|exec /usr/lib/org.nickvision.money/NickvisionMoney.GNOME|exec /snap/denaro/current/usr/lib/org.nickvision.money/NickvisionMoney.GNOME|" $CRAFT_PRIME/usr/bin/org.nickvision.money
      sed -e 's|Icon=org.nickvision.money|Icon=$SNAP/usr/share/icons/hicolor/scalable/apps/org.nickvision.money.svg|' -i $CRAFT_PRIME/usr/share/applications/org.nickvision.money.desktop
      mkdir $CRAFT_PRIME/usr/share/appdata/
      cp -r $CRAFT_PART_SRC_WORK/org.nickvision.money.metainfo.xml $CRAFT_PRIME/usr/share/appdata/
    parse-info: [ usr/share/appdata/org.nickvision.money.metainfo.xml ]
apps:
  denaro:
    command: usr/bin/org.nickvision.money
    desktop: usr/share/applications/org.nickvision.money.desktop
    extensions: [gnome]
    common-id: org.nickvision.money
    plugs:
      - home
