name: denaro # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2023.4.0-beta1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: denaro
summary: Manage your personal finances
description: |
  A personal finance manager
icon: org.nickvision.money.svg
source-code: https://github.com/nlogozzo/NickvisionMoney
issues: https://github.com/nlogozzo/NickvisionMoney/issues
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
package-repositories:
  - type: apt
    url: https://packages.microsoft.com/ubuntu/22.04/prod
    components: [main]
    suites: [jammy]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  - type: apt
    components: [kinetic]
    suites: [prebuilt-mpr]
    key-id: B70EAE798718E0FE2972DD0C4FE9F2C43D9428A0
    url: https://proget.makedeb.org
parts:
  denaro:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/nlogozzo/NickvisionMoney.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - just
      - blueprint-compiler
      - dotnet-sdk-7.0
    override-build: |
      craftctl default
      sed -e 's|Icon=org.nickvision.money|Icon=usr/share/icons/hicolor/scalable/apps/org.nickvision.money.svg|' -i NickvisionMoney.GNOME/org.nickvision.money.desktop
    override-prime: |
      craftctl default
      cd ~/parts/denaro/src/NickvisionMoney.GNOME
      just publish-self-contained /usr
      just install /root/prime
      sed -i "s|exec /usr/lib/org.nickvision.money/NickvisionMoney.GNOME|exec /snap/denaro/current/usr/lib/org.nickvision.money/NickvisionMoney.GNOME|" /root/prime/usr/bin/org.nickvision.money
    parse-info: [usr/share/metainfo/org.nickvision.money.metainfo.xml]
apps:
  denaro:
    command: usr/bin/org.nickvision.money
    desktop: usr/share/applications/org.nickvision.money.desktop
    extensions: [gnome]
    common-id: org.nickvision.money
    plugs:
      - home
