name: denaro # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2023.4.0' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: denaro
summary: Manage your personal finances
description: |
  A personal finance manager
icon: org.nickvision.money.svg
source-code: https://github.com/nlogozzo/NickvisionMoney
issues: https://github.com/nlogozzo/NickvisionMoney/issues
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
package-repositories:
  - type: apt
    url: https://packages.microsoft.com/ubuntu/22.04/prod
    components: [main]
    suites: [jammy]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
#  - type: apt
#    components: [kinetic]
#    suites: [prebuilt-mpr]
#    key-id: B70EAE798718E0FE2972DD0C4FE9F2C43D9428A0
#    url: https://proget.makedeb.org
parts:
  just:
    plugin: rust
    source-depth: 1
    source-tag: '1.13.0'
    source-type: git
    source: https://github.com/casey/just
    build-packages:
      - cargo
  denaro:
    after: [just]
    # See 'snapcraft plugins'
    plugin: dotnet
    source: https://github.com/NickvisionApps/Denaro.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-subdir: NickvisionMoney.GNOME
#    build-snaps:
#      - dotnet-sdk
    build-packages:
#      - just
      - blueprint-compiler
#      - dotnet-sdk-7.0
    override-build: |
      cd $CRAFT_PART_SRC_WORK
      just publish-self-contained /usr
      just install $CRAFT_PRIME
      sed -i "s|exec /usr/lib/org.nickvision.money/NickvisionMoney.GNOME|exec /snap/denaro/current/usr/lib/org.nickvision.money/NickvisionMoney.GNOME|" $CRAFT_PRIME/usr/bin/org.nickvision.money
      sed -e 's|Icon=org.nickvision.money|Icon=$SNAP/usr/share/icons/hicolor/scalable/apps/org.nickvision.money.svg|' -i $CRAFT_PRIME/usr/share/applications/org.nickvision.money.desktop
    parse-info: [ $CRAFT_PRIME/usr/share/metainfo/org.nickvision.money.metainfo.xml ]
apps:
  denaro:
    command: usr/bin/org.nickvision.money
    desktop: usr/share/applications/org.nickvision.money.desktop
    extensions: [gnome]
    common-id: org.nickvision.money
    plugs:
      - home
